apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:0c846066f814ac08abb12c18c9cf23f7d62ab842370406f7fecd018386868f4a
        name: container-image
        resources: {}
status: {}
