apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:9ec5235ed51d70af82bf3c5823ba29b05396a94a3f39b54bfad4db6b5127bfc5
        name: container-image
        resources: {}
status: {}
