apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:f12a6b9a84c28c439e3e57f3237dca67a572eeab44dcc2ad32a7eb7bec2da3fd
        name: container-image
        resources: {}
status: {}
