apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:9d5a80b9f86725d5cc86e81c9f951585afe98f11c073b84a859ca4dd91bdf9d6
        name: container-image
        resources: {}
status: {}
