apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:91f041d3cd9bae9117dc70fa976b3d312b6c0ee70f92992e29cd84eb313be1c6
        name: container-image
        resources: {}
status: {}
