apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:2fafe8e382494c9835334c1a8bb5d44eb0105821f44737d3489bfed361085f3e
        name: container-image
        resources: {}
status: {}
