apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-service-utils
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-service-utils
    app.kubernetes.io/part-of: release-service
  name: release-service-utils
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: release-service-utils
status:
  loadBalancer: {}
