apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-service
    app.kubernetes.io/part-of: release-service
  name: release-service
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: release-service
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:26a19afeb1c34d819e60d73b0ae8b942cc6ea8e74acb08431df3878c62858892
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 1
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
