apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-service
    app.kubernetes.io/part-of: release-service
  name: release-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: release-service
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:ef64adbe345e0b038ae731c13e14dd0937debb50ce3baf2c5af79d4023596dae
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 1
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
