apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-service
    app.kubernetes.io/part-of: release-service
  name: release-service
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: release-service
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service@sha256:a18ad6908f377899cec1c7a46f7cea4bb1695481c26ff89dc3b21ce9097cbe3b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 1
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
