apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-service
    app.kubernetes.io/part-of: release-service
  name: release-service
spec:
  ports:
  - port: 1
    targetPort: 1
  selector:
    app.kubernetes.io/instance: release-service
status:
  loadBalancer: {}
