apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service-utils
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service-utils@sha256:f5beeaafe664ea85a572e0688f13a1f588a015f79de7e7392127bc76298a2bd9
        name: container-image
        resources: {}
status: {}
