apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service-utils
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service-utils@sha256:b82b7d633c07e3780915b485f737fd7d7d7c196193607dccd349c13de3c7126d
        name: container-image
        resources: {}
status: {}
