apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service-utils
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service-utils@sha256:f8fc664cb30932bf6b8472d6eb6b54965a528253df1b55d4956016fe2b632f89
        name: container-image
        resources: {}
status: {}
