apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service-utils
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service-utils@sha256:a7a664402fda26ef64e297f88530ec0d1deefe087b51b16ad1230e67ccf2ca98
        name: container-image
        resources: {}
status: {}
