apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: release-service-utils
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service-utils@sha256:ae837b8320893d967f4ae3f928c2cc1b069f66ebb04fe7d5d4e52d63dce66ab6
        name: container-image
        resources: {}
status: {}
