apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-service-utils
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-service-utils
    app.kubernetes.io/part-of: release-service
  name: release-service-utilsuxph
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: release-service-utils
    weight: 100
status: {}
